// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ShortCode string
	LongUrl   string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}
