// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createShortCode = `-- name: CreateShortCode :one
INSERT INTO urls (short_code, long_url)
VALUES ($1, $2)
RETURNING short_code, long_url
`

type CreateShortCodeParams struct {
	ShortCode string
	LongUrl   string
}

type CreateShortCodeRow struct {
	ShortCode string
	LongUrl   string
}

func (q *Queries) CreateShortCode(ctx context.Context, arg CreateShortCodeParams) (CreateShortCodeRow, error) {
	row := q.db.QueryRow(ctx, createShortCode, arg.ShortCode, arg.LongUrl)
	var i CreateShortCodeRow
	err := row.Scan(&i.ShortCode, &i.LongUrl)
	return i, err
}

const getByLongUrl = `-- name: GetByLongUrl :one
SELECT short_code FROM urls WHERE long_url = $1
`

func (q *Queries) GetByLongUrl(ctx context.Context, longUrl string) (string, error) {
	row := q.db.QueryRow(ctx, getByLongUrl, longUrl)
	var short_code string
	err := row.Scan(&short_code)
	return short_code, err
}

const getLongUrl = `-- name: GetLongUrl :one
SELECT long_url FROM urls WHERE short_code = $1
`

func (q *Queries) GetLongUrl(ctx context.Context, shortCode string) (string, error) {
	row := q.db.QueryRow(ctx, getLongUrl, shortCode)
	var long_url string
	err := row.Scan(&long_url)
	return long_url, err
}
